### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by Zizzzzzzz** [wangxiao5791509/RGB-DVS-SOT-Baselines#3]
When I run the test.py of realtimeMDNet-visEvent-CMT(ALL)-python3, I meet:
`Traceback (most recent call last):
  File "test.py", line 120, in <module>
    iou_result, result_bb, fps, result_nobb = run_mdnet(img_list_vis, img_list_event, gt[0], gt, seq = seq, display=opts['visualize'])
  File "/home/yn/code/SOT/RGB-DVS-SOT-Baselines-main/realtimeMDNet-visEvent-CMT(ALL)-python3/tracker.py", line 136, in run_mdnet
    model = MDNet(opts['model_path'])
  File "./modules/model.py", line 110, in __init__
    self.load_model(model_path)
  File "./modules/model.py", line 247, in load_model
    self.fc_vis.load_state_dict(states['fc_vis'], strict=True)
KeyError: 'fc_vis'`
I'm wondering if there is something wrong with the pretrained weights(rt-mdnet.pth).

**Comment by Weihua-Wang** [comment]
I meet the same problem, the pretrained weights is not suit this model, the author use 'rt_mdnet_visEvent_CMT(ALL).pth'. You must train model to get the pth.
